#!/bin/bash
SERVER_PROPERTIES=server.properties
CRAFTBUKKIT_SERVER_JAR=craftbukkit-dev.jar

set -x 

cd $OPENSHIFT_DATA_DIR

if [ ! -e "$CRAFTBUKKIT_SERVER_JAR" ]; then
	wget "http://dl.bukkit.org/downloads/craftbukkit/get/01249_1.2.5-R5.0/craftbukkit.jar" -O $CRAFTBUKKIT_SERVER_JAR
fi

